#!/usr/bin/env bash
#
# Fetch or pull one or more git repositories at a specified location on your system.
#
# License: MIT License
#          Copyright (c) 2021-2022 Hunter T. (StrangeRanger)
#
########################################################################################
#### [ Variables ]


green="$(printf '\033[0;32m')"
blue="$(printf '\033[0;34m')"
cyan="$(printf '\033[0;36m')"
red="$(printf '\033[1;31m')"
nc="$(printf '\033[0m')"

version="v1.2.0"        # Program version.
maxdepth="-maxdepth 2"  # Peform recursive searches with a maximum depth of 2.
provided_path=false     # Validates that a path was provided.
git_repos=()            # List of paths to existing repositories on the system.
git_action="pull"
git_action_prog="Pulling"


#### End of [ Variables ]
########################################################################################
#### [ Functions ]


usage() {
    echo "Fetch or pull one or more git repositories at a specified location on your system."
    echo ""
    echo "Usage: ./${0##*/} [-r] [-f] [-d] -p <path>"
    echo "       ./${0##*/} -h"
    echo "       ./${0##*/} -v"
    echo ""
    echo "Options:"
    echo "  -h, --help       : Displays this help message."
    echo "  -p, --path       : Path to perform mass git pull/fetch on."
    echo "  -r, --recursive  : Recursively locate git repositories."
    echo "  -f, --fetch      : Fetch instead of pull from git repository."
    echo "  -d, --dry-run    : Show what would be done, without making any changes."
    echo "  -v, --version    : Display program version number."
}


#### End of [ Functions ]
########################################################################################
#### [ Options ]


# If no arguments are provided...
if [[ $# -eq 0 ]]; then
    usage
    exit 0
fi

# While there are still arguments to traverse...
while [[ -n $1 ]]; do
    case "$1" in
        "-h"|"--help")
            usage
            exit 0
            ;;
        "-p"|"--path")
            shift

            if hash realpath; then
                path="$(realpath "$1")"
            else
                ####
                # EXPLANATION:
                #   1. Gets the relative path as argument `"$1"`
                #   2. Gets the dirname part of that path: `dirname "$1"`
                #   3. `cd "$(dirname "$1")` into the relative dir and get the absolute
                #      path for it by running `pwd`
                #   4. Append the basename to the absolute path: `$(basename "$1")`
                #
                # This solution was found at the following link:
                # https://stackoverflow.com/questions/4175264/how-to-retrieve-absolute-path-given-relative/31605674#31605674
                #
                # '|| exit' makes sure that if the script is unable to change
                # directories, the script is exitted.
                ####
                path="$(cd "${1%/*}" || exit; pwd)/${1##*/}"
            fi
            provided_path=true
            ;;
        "-r"|"--recursive")
            unset maxdepth  # Remove the maxium depth of recursion.
            ;;
        "-f"|"--fetch")
            git_action="fetch"
            git_action_prog="Fetching"
            ;;
        "-d"|"--dry-run")
            dry_run="--dry-run"
            ;;
        "-v"|"--version")
            echo "Mass Git $version"
            exit 0
            ;;
        *)
            echo "${red}Invalid option:${nc} $1" >&2
            exit 1
            ;;
    esac
    shift
done

## Check if the provided path is a valid directory.
if "$provided_path"; then
    if [[ ! -d $path ]]; then
        if [[ -f $path ]]; then
            echo "${red}Invalid input:${nc} File was provided when a directory was" \
                "expected" >&2
        else
            echo "${red}Invalid input:${nc} Directory does not exist" >&2
        fi
        exit 1
    fi
else
    echo "${red}Invalid input:${nc} Missing required argument '-p <path>'"
    exit 1
fi


#### End of [ Options ]
########################################################################################
#### [ Main ]


## Store the location of all local repositories found.
## NOTE: $maxdepth is purposefully unquoted. Do not quote it!
# shellcheck disable=SC2086
while read -r -d $'\0'; do
    git_repos+=("${REPLY/%.git/}")
done < <(find "$path" $maxdepth -type d -name ".git" -prune -print0)

# If no local repositories were found...
# NOTE: Leave $git_repos as is. It's fine that only the first index of the array is
#       provided, as all we are trying to do is confirm whether or not a git initialized
#       directory was located.
# shellcheck disable=SC2128
if [[ -z $git_repos ]]; then
    echo "${red}ERROR:${nc} No git initialized directory could be found"
    exit 1
fi

[[ $dry_run = "--dry-run" ]] && echo "${cyan}==>${nc} Performing a dry-run..."

for repo_path in "${git_repos[@]}"; do
    echo "${blue}==>${nc} Changing directories to '$repo_path'..."
    cd "$repo_path" || {
        echo "${red}ERROR:${nc} Failed to change directories"
        exit 1
    }
    repo_name="$(git config --get remote.origin.url)"

    echo "${blue}==>${nc} $git_action_prog changes from '$repo_name'..."
    ## NOTE: $dry_run is purposefully unquoted. Do not quote it!
    # shellcheck disable=SC2086
    git "$git_action" $dry_run \
        || echo "${red}ERROR:${nc} Failed to $git_action changes from '$repo_name'"
done

echo "${green}==>${nc} Done"


#### End of [ Main ]
########################################################################################
