#!/usr/bin/env bash
#
# Fetch or pull one or more git repositories at a specified location on your system.
#
# Version: $C_VERSION
# License: MIT License
#          Copyright (c) 2021-2025 Hunter T. (StrangeRanger)
#
########################################################################################
####[ Global Variables ]################################################################


## ANSI color codes.
C_GREEN="$(printf '\033[0;32m')"
C_BLUE="$(printf '\033[0;34m')"
C_CYAN="$(printf '\033[0;36m')"
C_RED="$(printf '\033[1;31m')"
C_NC="$(printf '\033[0m')"
readonly C_GREEN C_BLUE C_CYAN C_RED C_NC

## Shorthanded variables for colorized output.
readonly C_INVALID_INPUT="${C_RED}Invalid input:${C_NC} "
readonly C_SUCCESS="${C_GREEN}==>${C_NC} "
readonly C_ERROR="${C_RED}ERROR:${C_NC} "
readonly C_INFO="${C_BLUE}==>${C_NC} "
readonly C_NOTE="${C_CYAN}==>${C_NC} "

## Program information.
readonly C_VERSION="v2.0.2"

## Other variables.
maxdepth="-maxdepth 2"  # Perform recursive searches with a maximum depth of 2.
git_repos=()  # List of paths to existing repositories on the system.
git_action="pull"
git_action_prog="Pulling"


####[ Functions ]#######################################################################


####
# Display the usage message for the program.
usage() {
    echo "Fetch or pull one or more git repositories at a specified location on your"
    echo "system."
    echo ""
    echo "Usage: ${0##*/} [-r] [-f] [-d] <path>"
    echo "       ${0##*/} -h"
    echo "       ${0##*/} -v"
    echo ""
    echo "Options:"
    echo "  -h, --help      : Displays this help message."
    echo "  -r, --recursive : Recursively locate git repositories."
    echo "  -f, --fetch     : Fetch instead of pull from git repository."
    echo "  -d, --dry-run   : Show what would be done, without making any changes."
    echo "  -v, --version   : Display program version number."
    exit 0
}


####[ Options ]#########################################################################


if (( $# == 0 )); then
    usage  # Will exit the script after execution.
fi

# While there are still arguments to traverse...
while [[ -n $1 ]]; do
    case "$1" in
        "-h"|"--help")
            usage  # Will exit the script after execution.
            ;;
        "-r"|"--recursive")
            unset maxdepth  # Remove the maximum depth of recursion.
            ;;
        "-f"|"--fetch")
            git_action="fetch"
            git_action_prog="Fetching"
            ;;
        "-d"|"--dry-run")
            dry_run="--dry-run"
            ;;
        "-v"|"--version")
            echo "Mass Git $C_VERSION"
            exit 0
            ;;
        -*)
            echo "${C_ERROR}Invalid argument: $1" >&2
            exit 2
            ;;
        *)
            if hash realpath; then
                path="$(realpath "$1" 2>/dev/null || echo "BAD MAGIC")"
            else
                path="$(cd "${1%/*}" || exit; pwd)/${1##*/}"
            fi
            ;;
    esac
    shift
done

if [[ -z $path ]]; then
    echo "${C_INVALID_INPUT}Missing required argument '<path>'" >&2
    exit 3
fi

if [[ -f $path ]]; then
    echo "${C_INVALID_INPUT}File was provided when a directory was expected" >&2
    exit 3
elif [[ ! -d $path ]]; then
    echo "${C_INVALID_INPUT}Directory '$path' does not exist" >&2
    exit 3
fi


####[ Main ]############################################################################


## Store the location of all local repositories found.
# shellcheck disable=SC2086
#   The $maxdepth variable should remain unquoted, such that when it's unset, it doesn't
#   cause an error.
while read -r -d $'\0'; do
    git_repos+=("${REPLY/%.git/}")
done < <(find "$path" $maxdepth -type d -name ".git" -prune -print0)

# If no local repositories were found...
# shellcheck disable=SC2128
#   We only need to check the first index of the array, as all we're doing is checking
#   if the array is empty or not.
if [[ -z $git_repos ]]; then
    echo "${C_ERROR}No git initialized directory could be found" >&2
    exit 1
fi

[[ $dry_run = "--dry-run" ]] && echo "${C_NOTE}Performing a dry-run..."

for repo_path in "${git_repos[@]}"; do
    echo "${C_INFO}Changing directories to '$repo_path'..."
    cd "$repo_path" || {
        echo "${C_ERROR}Failed to change directories" >&2
        exit 1
    }
    repo_name="$(git config --get remote.origin.url)"

    echo "${C_INFO}$git_action_prog changes from '$repo_name'..."
    # shellcheck disable=SC2086
    #   The $dry_run variable should remain unquoted, such that when it's not set, it
    #   doesn't cause an error.
    git "$git_action" $dry_run \
        || echo "${C_ERROR}Failed to $git_action changes from '$repo_name'" >&2
done

echo "${C_SUCCESS}Done"
